CREATE TABLE IF NOT EXISTS organisations (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS organisation_name ON organisations(name);

CREATE TABLE IF NOT EXISTS groups (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  organisation_id INTEGER,
  created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(organisation_id) REFERENCES organisations(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS group_name ON groups(organisation_id, name);

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  salt VARCHAR(100) NOT NULL,
  hashed_password VARCHAR(128) NOT NULL,
  organisation_id INTEGER,
  administrator BOOLEAN NOT NULL DEFAULT FALSE,
  created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(organisation_id) REFERENCES organisations(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS user_name ON users(organisation_id, name);

CREATE TABLE IF NOT EXISTS group_bindings (
  user_id INTEGER,
  group_id INTEGER,
  created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(group_id) REFERENCES groups(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS user_groups ON group_bindings(user_id, group_id);

CREATE TABLE IF NOT EXISTS sessions (
  user_id INTEGER,
  organisation_id INTEGER,
  session_id VARCHAR(100),
  refresh_id VARCHAR(100),
  expires BIGINT NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(organisation_id) REFERENCES organisations(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE OR REPLACE FUNCTION touch_updated()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.updated = NEW.updated THEN
    NEW.updated := now();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER organisations_updated
BEFORE UPDATE ON organisations
FOR EACH ROW
EXECUTE FUNCTION touch_updated();

CREATE OR REPLACE TRIGGER groups_updated
BEFORE UPDATE ON groups
FOR EACH ROW
EXECUTE FUNCTION touch_updated();

CREATE OR REPLACE TRIGGER groups_bindings_updated
BEFORE UPDATE ON group_bindings
FOR EACH ROW
EXECUTE FUNCTION touch_updated();

CREATE OR REPLACE TRIGGER users_updated
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION touch_updated();

