version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/tools"
      - "/test/integration"
    schedule:
      interval: "daily"
    groups:
      go-minor/patch-versions:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      go-minor/patch-security-versions:
        applies-to: security-updates
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/cmd/echo"
    schedule:
      interval: "daily"
    groups:
      docker-minor/patch-versions:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      docker-minor/patch-security-versions:
        applies-to: security-updates
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: golang
        versions:
          - "*rc*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      action-minor/patch-versions:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      action-minor/patch-security-versions:
        applies-to: security-updates
        update-types:
          - "minor"
          - "patch"
