# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    go-version-updates:
      applies-to: version-updates
      update-types:
        - "minor"
        - "patch"
    go-security-updates:
      applies-to: security-updates
      update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    docker-version-updates:
      applies-to: version-updates
      update-types:
        - "minor"
        - "patch"
    docker-security-updates:
      applies-to: security-updates
      update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      action-version-updates:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      action-security-updates:
        applies-to: security-updates
        update-types:
          - "minor"
          - "patch"
