version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
    schedule:
      interval: daily
      day: monday
    groups:
      go-updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gomod"
    directories:
      - "/tools"
    schedule:
      interval: weekly
      day: tuesday
    groups:
      go-tool-updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gomod"
    directories:
      - "/test/suites/integration"
      - "/test/suites/security"
    schedule:
      interval: weekly
      day: wednesday
    groups:
      go-test-updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: thursday
    groups:
      action-updates:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directories:
      - "/docker"
    schedule:
      interval: weekly
      day: friday
    groups:
      docker-updates:
        update-types:
          - "minor"
          - "patch"
