# yaml-language-server: $schema=https://spec.openapis.org/oas/3.0/schema/2024-10-18
openapi: "3.0.4"
info:
  version: 0.2.0
  title: Kerberos administration API.
  description: |
    The Kerberos administration API allows administrators manage a Kerberos deployment.
components:
  schemas:
    FlowMeta:
      type: object
      properties:
        name:
          type: string
        data:
          type: object
          anyOf:
            - $ref: "#/components/schemas/FlowMetaDataObservability"
            - $ref: "#/components/schemas/FlowMetaDataRouter"
            - $ref: "#/components/schemas/FlowMetaDataAuth"
            - $ref: "#/components/schemas/FlowMetaDataOAS"
            - $ref: "#/components/schemas/NoFlowMetaData"
      required:
        - name
        - data
      additionalProperties: false
    FlowMetaDataObservability:
      type: object
      properties:
        enabled:
          type: boolean
      required:
        - enabled
      additionalProperties: false
    FlowMetaDataRouter:
      type: object
      additionalProperties: false
      properties:
        backends:
          type: array
          items:
            $ref: "#/components/schemas/FlowMetaDataRouterBackend"
    FlowMetaDataRouterBackend:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        host:
          type: string
        port:
          type: integer
      required:
        - name
        - host
        - port
    FlowMetaDataAuth:
      type: object
      additionalProperties: false
      properties:
        methods:
          $ref: "#/components/schemas/FlowMetaDataAuthMethods"
        scheme:
          $ref: "#/components/schemas/FlowMetaDataAuthScheme"
    FlowMetaDataAuthMethods:
      type: object
      additionalProperties: false
      properties:
        basic:
          $ref: "#/components/schemas/FlowMetaDataAuthMethodBasic"
    FlowMetaDataAuthMethodBasic:
      type: object
      additionalProperties: false
    FlowMetaDataAuthScheme:
      type: object
      additionalProperties: false
      properties:
        mappings:
          type: array
          items:
            $ref: "#/components/schemas/FlowMetaDataAuthSchemeMapping"
    FlowMetaDataAuthSchemeMapping:
      type: object
      additionalProperties: false
      properties:
        backend:
          type: string
        method:
          type: string
        exempt:
          type: array
          items:
            type: string
        authorization:
          $ref: "#/components/schemas/FlowMetaDataAuthSchemeMappingAuthorization"
      required:
        - backend
        - method
    FlowMetaDataAuthSchemeMappingAuthorization:
      type: object
      additionalProperties: false
      properties:
        groups:
          type: array
          items:
            type: string
        paths:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
    FlowMetaDataOAS:
      type: object
      additionalProperties: false
      properties:
        backends:
          type: array
          items:
            type: string
    NoFlowMetaData:
      type: object
      description: No metadata for the flow component.
      additionalProperties: false
    APIErrorResponse:
      type: object
      additionalProperties: false
      properties:
        errors:
          type: array
          items:
            type: string
          minItems: 1
      required:
        - errors
  headers:
    sessionid:
      required: true
      description: A session ID.
      schema:
        type: string
  securitySchemes:
    sessionid:
      type: apiKey
      in: header
      name: x-krb-session

security:
  - sessionid: []

paths:
  # Log the superuser in.
  /api/admin/superuser/login:
    post:
      security: []
      operationId: LoginSuperuser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                clientId:
                  type: string
                  minLength: 1
                clientSecret:
                  type: string
                  minLength: 1
              required:
                - clientId
                - clientSecret
      responses:
        "204":
          headers:
            x-krb-session:
              $ref: "#/components/headers/sessionid"
          description: Logged the superuser in.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIErrorResponse"
          description: Bad request.
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIErrorResponse"
          description: Failed to log the superuser in.
        "429":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIErrorResponse"
          description: Rate limited.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIErrorResponse"
          description: Internal error.

  # Log the superuser out.
  /api/admin/superuser/logout:
    post:
      operationId: LogoutSuperuser
      responses:
        "204":
          description: Logged the superuser out.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIErrorResponse"
          description: Internal error.

  # Flow management endpoints.
  /api/admin/flow:
    get:
      operationId: GetFlow
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FlowMeta"
          description: Got the flow successfully.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIErrorResponse"
          description: Internal error.

  /api/admin/oas/{backend}:
    get:
      operationId: GetBackendOAS
      parameters:
        - name: backend
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/yaml:
              schema:
                type: object
                additionalProperties: true
          description: Got the backend OAS successfully.
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIErrorResponse"
          description: Backend not found.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIErrorResponse"
          description: Internal error.
