services:
  prometheus:
    image: "prom/prometheus:v3.3.1"
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: "grafana/grafana:12.0.0"
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/grafana-datasources.yml
      - ./grafana/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/grafana-dashboards.yml
      - ./grafana/dashboard.json:/var/lib/grafana/dashboard.json
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

  # jaeger:
  #   image: "jaegertracing/all-in-one:1.50"
  #   ports:
  #     - 5775:5775/udp
  #     - 6831:6831/udp
  #     - 6832:6832/udp
  #     - 5778:5778
  #     - 14268:14268
  #     - 14250:14250
  #     - 16686:16686
  #     - 14267:14267
  #   environment:
  #     COLLECTOR_ZIPKIN_HTTP_PORT: 9411
