services:
  prometheus:
    image: "prom/prometheus:v3.3.1"
    ports:
      - ${PROM_PORT}:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: "grafana/grafana:12.0.0"
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - ./grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/grafana-datasources.yml
      - ./grafana/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/grafana-dashboards.yml
      - ./grafana/prometheus.json:/var/lib/grafana/prometheus.json
      - ./grafana/kerberos_runtime.json:/var/lib/grafana/kerberos_runtime.json
      - ./grafana/kerberos_http.json:/var/lib/grafana/kerberos_http.json
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

  jaeger:
    image: "jaegertracing/jaeger:2.6.0"
    ports:
      - 4317:4317
      - 16686:16686
    environment:
      - COLLECTOR_OTLP_ENABLED=true