//go:build go1.22

// Package adminapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package adminapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	SessionidScopes = "sessionid.Scopes"
)

// APIErrorResponse defines model for APIErrorResponse.
type APIErrorResponse struct {
	Errors []string `json:"errors"`
}

// FlowMeta defines model for FlowMeta.
type FlowMeta struct {
	Data map[string]interface{} `json:"data"`
	Name string                 `json:"name"`
}

// LoginSuperuserJSONBody defines parameters for LoginSuperuser.
type LoginSuperuserJSONBody struct {
	ClientId     string `json:"clientId"`
	ClientSecret string `json:"clientSecret"`
}

// LoginSuperuserJSONRequestBody defines body for LoginSuperuser for application/json ContentType.
type LoginSuperuserJSONRequestBody LoginSuperuserJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/admin/flow)
	GetFlow(w http.ResponseWriter, r *http.Request)

	// (GET /api/admin/oas/{backend})
	GetBackendOAS(w http.ResponseWriter, r *http.Request, backend string)

	// (POST /api/admin/superuser/login)
	LoginSuperuser(w http.ResponseWriter, r *http.Request)

	// (POST /api/admin/superuser/logout)
	LogoutSuperuser(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetFlow operation middleware
func (siw *ServerInterfaceWrapper) GetFlow(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionidScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFlow(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBackendOAS operation middleware
func (siw *ServerInterfaceWrapper) GetBackendOAS(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "backend" -------------
	var backend string

	err = runtime.BindStyledParameterWithOptions("simple", "backend", r.PathValue("backend"), &backend, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "backend", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionidScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBackendOAS(w, r, backend)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoginSuperuser operation middleware
func (siw *ServerInterfaceWrapper) LoginSuperuser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginSuperuser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LogoutSuperuser operation middleware
func (siw *ServerInterfaceWrapper) LogoutSuperuser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionidScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LogoutSuperuser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/admin/flow", wrapper.GetFlow)
	m.HandleFunc("GET "+options.BaseURL+"/api/admin/oas/{backend}", wrapper.GetBackendOAS)
	m.HandleFunc("POST "+options.BaseURL+"/api/admin/superuser/login", wrapper.LoginSuperuser)
	m.HandleFunc("POST "+options.BaseURL+"/api/admin/superuser/logout", wrapper.LogoutSuperuser)

	return m
}

type GetFlowRequestObject struct {
}

type GetFlowResponseObject interface {
	VisitGetFlowResponse(w http.ResponseWriter) error
}

type GetFlow200JSONResponse []FlowMeta

func (response GetFlow200JSONResponse) VisitGetFlowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetFlow500JSONResponse APIErrorResponse

func (response GetFlow500JSONResponse) VisitGetFlowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetBackendOASRequestObject struct {
	Backend string `json:"backend"`
}

type GetBackendOASResponseObject interface {
	VisitGetBackendOASResponse(w http.ResponseWriter) error
}

type GetBackendOAS200ApplicationyamlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetBackendOAS200ApplicationyamlResponse) VisitGetBackendOASResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/yaml")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetBackendOAS404JSONResponse APIErrorResponse

func (response GetBackendOAS404JSONResponse) VisitGetBackendOASResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetBackendOAS500JSONResponse APIErrorResponse

func (response GetBackendOAS500JSONResponse) VisitGetBackendOASResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LoginSuperuserRequestObject struct {
	Body *LoginSuperuserJSONRequestBody
}

type LoginSuperuserResponseObject interface {
	VisitLoginSuperuserResponse(w http.ResponseWriter) error
}

type LoginSuperuser204ResponseHeaders struct {
	XKrbSession string
}

type LoginSuperuser204Response struct {
	Headers LoginSuperuser204ResponseHeaders
}

func (response LoginSuperuser204Response) VisitLoginSuperuserResponse(w http.ResponseWriter) error {
	w.Header().Set("x-krb-session", fmt.Sprint(response.Headers.XKrbSession))
	w.WriteHeader(204)
	return nil
}

type LoginSuperuser400JSONResponse APIErrorResponse

func (response LoginSuperuser400JSONResponse) VisitLoginSuperuserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type LoginSuperuser401JSONResponse APIErrorResponse

func (response LoginSuperuser401JSONResponse) VisitLoginSuperuserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type LoginSuperuser429JSONResponse APIErrorResponse

func (response LoginSuperuser429JSONResponse) VisitLoginSuperuserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type LoginSuperuser500JSONResponse APIErrorResponse

func (response LoginSuperuser500JSONResponse) VisitLoginSuperuserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LogoutSuperuserRequestObject struct {
}

type LogoutSuperuserResponseObject interface {
	VisitLogoutSuperuserResponse(w http.ResponseWriter) error
}

type LogoutSuperuser204Response struct {
}

func (response LogoutSuperuser204Response) VisitLogoutSuperuserResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type LogoutSuperuser500JSONResponse APIErrorResponse

func (response LogoutSuperuser500JSONResponse) VisitLogoutSuperuserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/admin/flow)
	GetFlow(ctx context.Context, request GetFlowRequestObject) (GetFlowResponseObject, error)

	// (GET /api/admin/oas/{backend})
	GetBackendOAS(ctx context.Context, request GetBackendOASRequestObject) (GetBackendOASResponseObject, error)

	// (POST /api/admin/superuser/login)
	LoginSuperuser(ctx context.Context, request LoginSuperuserRequestObject) (LoginSuperuserResponseObject, error)

	// (POST /api/admin/superuser/logout)
	LogoutSuperuser(ctx context.Context, request LogoutSuperuserRequestObject) (LogoutSuperuserResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetFlow operation middleware
func (sh *strictHandler) GetFlow(w http.ResponseWriter, r *http.Request) {
	var request GetFlowRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFlow(ctx, request.(GetFlowRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFlow")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFlowResponseObject); ok {
		if err := validResponse.VisitGetFlowResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetBackendOAS operation middleware
func (sh *strictHandler) GetBackendOAS(w http.ResponseWriter, r *http.Request, backend string) {
	var request GetBackendOASRequestObject

	request.Backend = backend

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBackendOAS(ctx, request.(GetBackendOASRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBackendOAS")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBackendOASResponseObject); ok {
		if err := validResponse.VisitGetBackendOASResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LoginSuperuser operation middleware
func (sh *strictHandler) LoginSuperuser(w http.ResponseWriter, r *http.Request) {
	var request LoginSuperuserRequestObject

	var body LoginSuperuserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LoginSuperuser(ctx, request.(LoginSuperuserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginSuperuser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginSuperuserResponseObject); ok {
		if err := validResponse.VisitLoginSuperuserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LogoutSuperuser operation middleware
func (sh *strictHandler) LogoutSuperuser(w http.ResponseWriter, r *http.Request) {
	var request LogoutSuperuserRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LogoutSuperuser(ctx, request.(LogoutSuperuserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LogoutSuperuser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutSuperuserResponseObject); ok {
		if err := validResponse.VisitLogoutSuperuserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xWzW7bPBB8FYLfd1QkJ3UP1c1Bm8BIigRxb64PtLiWmVAkS66aCobevSAlW1bkGHAP",
	"Rk5WxP2ZzMwutaGZLoxWoNDRdEPXwDjY8OjAOaGV4P4PDi6zwqDQiqZ0QtpDMv0a04ha+FUKC5ymaEuI",
	"qMvWUDCfh5UBmlKHVqic1nW9PQwtJo/Tb9Zq+wTOaOXAv2OcC9+GyUerDVgU4Gi6YtJBRM3eqw0Fnxue",
	"BELhDvSLaCHUtDm8jLanzFpWUY+lAz7fVlvswvTyGTL0RW6kfv0OyE7Ex9mxlIaqQS/FCjjEXB9siIqa",
	"DkPEnmXISiuwmnm2YSio8Do2atNtU/rn4sUuL9o42vFlxB1UjXpCrfTQED/WQO7ALsFqRxgvhBIOLfOn",
	"ZPI4JUxK/do70daRgimWA2FdKgcjdVWAwvhnACBQegRHanv//QbrGiCj+CoeeRq1AcWMoCn9FI/iMY2o",
	"YbgOPCTMiCQUSlZSv/pXOaD/8eKEwlNOU3oL6IUP/m78GdKvRiP/k2mFoEIaM0aKLCQmz87j2OyNwM6b",
	"/1tY0ZT+l3Qjl7TDkOwcVg9cWkdvyL7VSHANxIMnrswycG5VSlnFPvvzifCOoRrM5wE0U4VgFZMkzE/s",
	"Q+pon2PNXLJZsuwFFK+PkX3dxDxMZkEtywrAsIvmrV29gp1Z25InrZ/FSVpWrJB9sk6Y5Pd1a4GTh8ls",
	"KN94ND6rfC3pRGkkK10q/jFN5EoDtnRgE6lzEbob7Q746N4fz7bRrTnA4bXm1Un/Un+VZ1KAwmlYnYVQ",
	"96ByXO/fKd2N04TOILONz4+Gv1nruzZvyiwO2qvv+3rg7fFwUd/rPAcebLijlAjll+je1d+/B97Rt41P",
	"umslgBqf2TrXjJNW43aALs/a/4YJ6RnVROr8ALEe0tWXs0J6YghEikIgfJRx7j5IaDpfHBtuXeLR6dYl",
	"9sf7nyyvS/wwi65PTu87bb6oF/XfAAAA//9A9FMUpAsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
