# yaml-language-server: $schema=https://spec.openapis.org/oas/3.0/schema/2024-10-18
openapi: "3.0.4"
info:
  version: 0.1.0
  title: Kerberos basic authentication API.
  description: |
    The Kerberos basic authentication API provides support for managing user accounts, groups,
    and organisations.
    
    Organisations provide support for user isolation. A user in org. A cannot access information
    protected by org. B. Organisations provide isolation by associating sets of users with an
    organisation entity, the target backend will receive an information element pointing out 
    which organisation a request was made for. This method of isolation only works if Kerberos
    is the only possible path to reach the target backend service, or the information element 
    will be possible to spoof.

    The basic authentication API provides user group support, allowing for role-based authorization.
components:
  schemas:
    GenericErrorResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    User:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    Group:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    UserGroups:
      type: array
      items:
        type: string
    Organisation:
      type: object
      properties:
        name:
          type: string
      required:
        - name
  headers:
    sessionid:
      required: true
      description: A session ID.
      schema:
        type: string
  parameters:
    userid:
      name: userID
      in: path
      required: true
      description: A user ID.
      schema:
        type: string
    orgid:
      name: orgID
      in: path
      required: true
      description: An organisation ID.
      schema:
        type: string
    groupid:
      name: groupID
      in: path
      required: true
      description: A group ID.
      schema:
        type: string

paths:
  /login:
    post:
      operationId: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '204':
          headers:
            x-krb-session:
              $ref: "#/components/headers/sessionid"
          description: Logged a user in.
        '403':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericErrorResponse"
          description: Failed to log a user in.
        '500':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericErrorResponse"
          description: Internal error.

  /logout:
    post:
      operationId: Logout
      responses:
        '204':
          description: Logged a user out.
        '500':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericErrorResponse"
          description: Internal error.
  

  # When invoking the /user path, the requests are automatically executed on the
  # organisation the executing user belongs to. This is ALWAYS the case, except when creating the
  # first user, which is done behind the scenes when creating a new organisation.
  /user:
    post:
      operationId: CreateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        '200':
          description: Created a new user.
        '500':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericErrorResponse"
          description: Internal error.
    get:
      operationId: ListUsers
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
          description: Listed all users.
        '500':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericErrorResponse"
          description: Internal error.

  /user/{userID}:
    parameters:
      - "$ref": "#/components/parameters/userid"
    get:
      operationId: GetUser
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
          description: Got a user.
        '500':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericErrorResponse"
          description: Internal error.
    put:
      operationId: UpdateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
          description: Updated a user.
        '500':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericErrorResponse"
          description: Internal error.
    delete:
      operationId: DeleteUser
      responses:
        '204':
          description: Deleted a user.
        '500':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericErrorResponse"
          description: Internal error.

  /user/{userID}/group:
    parameters:
      - "$ref": "#/components/parameters/userid"
    put:
      operationId: UpdateUserGroups
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserGroups"
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserGroups"
          description: Updated the user's group bindings.
        '500':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericErrorResponse"
          description: Internal error.
    get:
      operationId: GetUserGroups
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserGroups"
          description: Got a user's group bindings.
        '500':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericErrorResponse"
          description: Internal error.

  /user/{userID}/password:
    parameters:
      - "$ref": "#/components/parameters/userid"
    put:
      operationId: ChangePassword
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
              required:
                - password
      responses:
        '204':
          description: Changed a user's password.
        '500':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericErrorResponse"
          description: Internal error.

  # Creating a new organisation will automatically create an admin user.
  /organisation:
    post:
      operationId: CreateOrganisation
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Organisation"
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Organisation"
                  - type: object
                    properties:
                      adminUsername:
                        type: string
                      adminPassword:
                        type: string
                    required:
                      - adminUsername
                      - adminPassword
          description: Created a new organisation.
        '500':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericErrorResponse"
          description: Internal error.
    get:
      operationId: ListOrganisations
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Organisation"
          description: Listed all organisations.
        '500':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericErrorResponse"
          description: Internal error.

  /organisation/{orgID}:
    parameters:
      - "$ref": "#/components/parameters/orgid"
    put:
      operationId: UpdateOrganisation
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Organisation"
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organisation"
          description: Updated an organisation.
        '500':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericErrorResponse"
          description: Internal error.
    get:
      operationId: GetOrganisation
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organisation"
          description: Got an organisation.
        '500':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericErrorResponse"
          description: Internal error.
    delete:
      operationId: DeleteOrganisation
      responses:
        '204':
          description: Deleted an organisation.
        '500':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericErrorResponse"
          description: Internal error.

  /organisation/{orgID}/group:
    parameters:
      - "$ref": "#/components/parameters/orgid"
    post:
      operationId: CreateGroup
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Group"
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Group"
          description: Created a group in the organisation.
        '500':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericErrorResponse"
          description: Internal error.
    get:
      operationId: ListGroups
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Group"
              example:
                - name: Group 1
                - name: Group 2
          description: Listed all groups in the organisation.
        '500':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericErrorResponse"
          description: Internal error.

  /organisation/{orgID}/group/{groupID}:
    parameters:
      - "$ref": "#/components/parameters/orgid"
      - "$ref": "#/components/parameters/groupid"
    put:
      operationId: UpdateGroup
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Group"
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Group"
          description: Updated a group.
        '500':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericErrorResponse"
          description: Internal error.
    get:
      operationId: GetGroup
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Group"
          description: Got a group.
        '500':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericErrorResponse"
          description: Internal error.
    delete:
      operationId: DeleteGroup
      responses:
        '204':
          description: Deleted a group.
        '500':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericErrorResponse"
          description: Internal error.
