{
 "title": "Prometheus status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Target up status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Target information",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by (job, instance, \"service.name\") (target_info)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Scrape series added",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    { "expr": "scrape_series_added", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Scrape duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Samples scraped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "scrape_samples_scraped", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Scrape samples post metric relableing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "scrape_samples_post_metric_relabeling",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}