{
 "title": "Kerberos",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{\"runtime.uptime_milliseconds_total\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CGO calls",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "{\"process.runtime.go.cgo.calls\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{\"process.runtime.go.goroutines\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap: allocated bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "{\"process.runtime.go.mem.heap_alloc_bytes\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Heap: idle bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "{\"process.runtime.go.mem.heap_idle_bytes\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Heap: inuse bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "{\"process.runtime.go.mem.heap_inuse_bytes\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Heap: objects",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{\"process.runtime.go.mem.heap_objects\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Heap: released bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "{\"process.runtime.go.mem.heap_released_bytes\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Heap: sys bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "{\"process.runtime.go.mem.heap_sys_bytes\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Memory: live objects",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{\"process.runtime.go.mem.live_objects\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Memory: total lookups",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{\"process.runtime.go.mem.lookups_total\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Memory: total lookups",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{\"process.runtime.go.mem.lookups_total\"}",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC pause ns sum",
     "type": "stat",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{\"process.runtime.go.gc.pause_ns_sum\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "GC pause ns count",
     "type": "stat",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 62 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{\"process.runtime.go.gc.pause_ns_count\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "GC pause ns bucket",
     "type": "stat",
     "gridPos": { "h": 19, "w": 16, "x": 0, "y": 70 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{\"process.runtime.go.gc.pause_ns_bucket\"}",
       "legendFormat": "{{job}}: le {{le}}"
      }
     ]
    },
    {
     "title": "GC count total",
     "type": "stat",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 72 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{\"process.runtime.go.gc.count_total\"}",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  { "title": "Observability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "promhttp gathering errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "promhttp_metric_handler_errors_total",
     "legendFormat": "{{job}}: cause = {{cause}}"
    }
   ]
  }
 ]
}