#! /bin/bash

set -e

if [ -z $1 ]; then
  echo "no org identifier given"
  exit 1
fi

echo "Running organisation creation..."
org=$(curl http://localhost:30000/api/auth/basic/organisations \
  -X POST \
  -H "Content-Type: application/json" \
  --data "{\"name\": \"Corp $1\"}")
echo "Created org:"
echo $org

orgid=$(echo $org | jq -r .id)
userid=$(echo $org | jq -r .adminUserId)
pass=$(echo $org | jq -r .adminPassword)
user=$(echo $org | jq -r .adminUsername)

echo "Org ID: $orgid"
echo "Username: $user"
echo "UserID: $userid"
echo "Password: $pass"

curl -i localhost:30000/api/auth/basic/login \
  -X POST \
  -H "Content-Type: application/json" \
  --data "{\"username\": \"$user\", \"password\": \"$pass\"}" > login

echo "Login result:"
cat login

session=$(cat login | grep X-Krb-Session | awk -F': ' '{print $2}' | tr -d '\r\n ')
echo "Got session: $session"

echo "Changing password..."
data="{\"oldPassword\": \"$pass\", \"password\": \"abc123\"}"
echo "Body: $data"

curl -i localhost:30000/api/auth/basic/users/$userid/password \
  -X PUT \
  -H "x-krb-session: $session" \
  --data "$data"

echo "Creating base groups..."
curl -i localhost:30000/api/auth/basic/organisations/$orgid/groups \
  -X POST \
  -H "x-krb-session: $session" \
  --data '{"name": "Staff"}'
curl -i localhost:30000/api/auth/basic/organisations/$orgid/groups \
  -X POST \
  -H "x-krb-session: $session" \
  --data '{"name": "Servant"}'
curl -i localhost:30000/api/auth/basic/organisations/$orgid/groups \
  -X POST \
  -H "x-krb-session: $session" \
  --data '{"name": "Admin"}'

echo "Creating group bindings..."
curl -i localhost:30000/api/auth/basic/users/$userid/groups \
  -X PUT \
  -H "x-krb-session: $session" \
  --data '["Staff", "Servant"]'
