name: Main branch protection

run-name: Main branch protection - ${{ github.event.head_commit.message }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

# Should prevent concurrency on a per-branch basis.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false

permissions:
  checks: write
  contents: read
  packages: write
  pull-requests: read
  security-events: write

jobs:
  static-analysis:
    uses: ./.github/workflows/callable-static-analysis.yaml
    secrets: inherit

  build:
    uses: ./.github/workflows/callable-build.yaml
    secrets: inherit

  image:
    uses: ./.github/workflows/callable-image.yaml
    secrets: inherit
    with:
      version: unstable
      push: true

  integration-test:
    needs: image
    uses: ./.github/workflows/callable-integration-test.yaml
    secrets: inherit
    with:
      version: unstable

  security-test:
    needs: image
    uses: ./.github/workflows/callable-security-test.yaml
    secrets: inherit
    with:
      version: unstable
