name: "PoC: Push Docker image to AWS ECR"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to push, applies to both echo and Kerberos."
        required: false
        type: string
        default: "latest"

permissions:
  contents: read
  id-token: write

jobs:
  push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Obtain temporary AWS credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: ${{ vars.POC_AWS_ROLE_ARN }}
          aws-region: ${{ vars.POC_AWS_REGION }}
          allowed-account-ids: ${{ vars.POC_AWS_ACCOUNT_ID }}
          role-session-name: github-${{ github.run_id }}

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6

      - name: Push images
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        run: |
          docker pull ghcr.io/${{ github.repository }}:${{ inputs.version }}
          docker pull ghcr.io/${{ github.repository }}/echo:${{ inputs.version }}

          docker tag ghcr.io/${{ github.repository }}:${{ inputs.version }} $ECR_REGISTRY/${{ vars.POC_AWS_REPO_KRB }}:${{ inputs.version }}
          docker tag ghcr.io/${{ github.repository }}/echo:${{ inputs.version }} "$ECR_REGISTRY/${{ vars.POC_AWS_REPO_KRB_ECHO }}:${{ inputs.version }}"

          docker push $ECR_REGISTRY/${{ vars.POC_AWS_REPO_KRB }}:${{ inputs.version }}
          docker push $ECR_REGISTRY/${{ vars.POC_AWS_REPO_KRB_ECHO }}:${{ inputs.version }}
