name: "PoC: Push Docker image to AWS ECR"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to push, applies to both echo and Kerberos."
        required: false
        type: string
        default: "latest"

permissions:
  contents: read
  id-token: write

jobs:
  push-images:
    runs-on: ubuntu-latest
    environment: poc-aws
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0

      - name: Obtain temporary AWS credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: ${{ vars.POC_AWS_ROLE_ARN }}
          aws-region: ${{ vars.POC_AWS_REGION }}
          allowed-account-ids: ${{ vars.POC_AWS_ACCOUNT_ID }}
          role-session-name: github-${{ github.run_id }}

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd # v2.1.7

      - name: Kerberos metadata
        id: krb-meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ${{ steps.ecr-login.outputs.registry }}/${{ vars.POC_AWS_REPO_KRB }}
          tags: |
            type=raw,value=${{ inputs.version }}

      - name: Build and push kerberos
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: docker/krb.Dockerfile
          push: true
          target: poc-runtime
          build-args: |
            VERSION=${{ inputs.version }}
          tags: ${{ steps.krb-meta.outputs.tags }}
          labels: ${{ steps.krb-meta.outputs.labels }}
          cache-from: type=gha,scope=kerberos
          cache-to: type=gha,scope=kerberos,mode=max

      - name: Echo metadata
        id: echo-meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ${{ steps.ecr-login.outputs.registry }}/${{ vars.POC_AWS_REPO_KRB_ECHO }}
          tags: |
            type=raw,value=${{ inputs.version }}
          labels: |
            org.opencontainers.image.title=echo
            org.opencontainers.image.description=A simple HTTP echo server that echoes back request body and headers.

      - name: Build and push echo
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: docker/echo.Dockerfile
          push: true
          build-args: |
            VERSION=${{ inputs.version }}
          tags: ${{ steps.echo-meta.outputs.tags }}
          labels: ${{ steps.echo-meta.outputs.labels }}
          cache-from: type=gha,scope=echo
          cache-to: type=gha,scope=echo,mode=max
