name: Deploy static content to Pages

run-name: Deploy pages - ${{ github.event.head_commit.message }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  checksum-api-pages:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get API documentation checksum
        id: checksum
        run: |
          checksum=$(find ./pages/ -type f | xargs cat | md5sum | awk '{print $1}')
          echo "checksum=$checksum" >> $GITHUB_OUTPUT
          echo "Checksum of API documentation: $checksum"
          echo "$checksum" > checksum

      - name: Cache
        id: cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.3
        with:
          path: checksum
          key: api-pages-${{ steps.checksum.outputs.checksum }}

  deploy-api-pages:
    needs: checksum-api-pages
    if: ${{ needs.checksum-api-pages.outputs.cache-hit != 'true' }}
    environment:
      name: api-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: "pages/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v4.0.2
