name: Deploy static content to Pages

run-name: "Deploy pages - ${{ format('{0} #{1}', github.ref_name, github.run_number) }}"

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  checksum-api-pages:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Get API documentation checksum
        id: checksum
        run: |
          checksum=$(find ./pages/ -type f | xargs cat | md5sum | awk '{print $1}')
          echo "checksum=$checksum" >> $GITHUB_OUTPUT
          echo "Checksum of API documentation: $checksum"
          echo "$checksum" > checksum

      - name: Cache
        id: cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.3
        with:
          path: checksum
          key: api-pages-${{ steps.checksum.outputs.checksum }}

  deploy-api-pages:
    needs: checksum-api-pages
    if: ${{ needs.checksum-api-pages.outputs.cache-hit != 'true' }}
    environment:
      name: api-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: "pages/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v4.0.2
